# Generated by Django 6.1.1 on 2026-10-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='projetos/')),
                ('tecnologias', models.CharField(help_text='Ex: Python, Django, Tailwind', max_length=200)),
                ('link_github', models.URLField(blank=True, null=True)),
                ('link_deploy', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
